services:
#    brix_i_tbrixmond.example:
#        class: BrixIT\brixmondBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    user_notifier:
        class: BrixIT\brixmondBundle\Util\UserNotifier
        calls:
              - [ setContainer,[ @service_container ] ]