services:
#    brix_i_tbrixmond.example:
#        class: BrixIT\brixmondBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }

    user_notifier:
        class: BrixIT\brixmondBundle\Util\UserNotifier
        calls:
              - [ setContainer,[ @service_container ] ]
    watch_runner:
        class: BrixIT\brixmondBundle\Util\WatchRunner
        calls:
              - [ setContainer,[ @service_container ] ]
    message_manager:
        class: BrixIT\brixmondBundle\Util\MessageManager
        calls:
              - [ setContainer,[ @service_container ] ]